const CONFIG={APPS_SCRIPT_URL:"https://script.google.com/macros/s/AKfycbxlpGiHqEw2H_qPHZKkSWsXsiFGFUDRPw8qtdPj0twoUsdCeY5f89gY3T4GkJ-qTcxakA/exec"};
const data={customers:[],payments:[],packages:[]};
const money=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(n)||0);
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const badge=s=>`<span class="badge ${String(s).toLowerCase()==="lunas"||String(s).toLowerCase()==="aktif"?"ok":"danger"}">${esc(s||"-")}</span>`;
let route="dashboard",currentUser=null;

function api(action,params={}){return new Promise((resolve,reject)=>{const cb="waliNetCb_"+Date.now()+"_"+Math.floor(Math.random()*100000),script=document.createElement("script"),q=new URLSearchParams({action,...params,prefix:cb,callback:cb,_ts:Date.now()}),timer=setTimeout(()=>{cleanup();reject(new Error("API tidak merespons. Pastikan deployment Apps Script dapat diakses oleh Siapa saja."))},20000);window[cb]=result=>{clearTimeout(timer);cleanup();resolve(result)};function cleanup(){delete window[cb];if(script.parentNode)script.parentNode.removeChild(script)}script.onerror=()=>{clearTimeout(timer);cleanup();reject(new Error("Gagal terhubung ke server WaliNet."))};script.src=CONFIG.APPS_SCRIPT_URL+"?"+q.toString();document.body.appendChild(script)})}

function isAdmin(){return String(currentUser?.role||"").trim().toLowerCase()==="admin"||String(currentUser?.role||"").trim().toLowerCase()==="administrator"}
function logout(){sessionStorage.removeItem("walinet_session");currentUser=null;route="dashboard";document.getElementById("app").classList.add("hidden");showLogin()}

async function loadRemoteData(){try{const [customers,payments,packages]=await Promise.all([api("customers",currentUser?.token?{token:currentUser.token}:{}),api("payments"),api("packages")]);if(!customers.success)throw new Error(customers.message||"Gagal mengambil pelanggan.");data.customers=(customers.data||[]).map(x=>({id:x["ID Pelanggan"]||x["ID"]||"",name:x["Nama"]||"",phone:x["No HP"]||x["Nomor HP"]||"",package:x["Nama Paket"]||x["Paket"]||x["ID Paket"]||"-",packageId:x["ID Paket"]||x["Paket"]||"",price:Number(x["Harga"]||0)||0,due:x["Jatuh Tempo"]||x["Tanggal Jatuh Tempo"]||"",status:x["Status"]||"Aktif",address:x["Alamat"]||"",type:x["Tipe"]||""}));data.payments=(payments.data||[]).map(x=>({id:x["ID Pembayaran"]||"",customerId:x["ID Pelanggan"]||"",customer:x["Nama"]||"",period:x["Periode"]||x["Keterangan"]||"",amount:Number(x["Nominal"]||x["Jumlah"]||0)||0,date:x["Tanggal Bayar"]||x["Tanggal"]||"",method:x["Metode"]||"",status:x["Status"]||""}));data.packages=packages.data||[];return true}catch(e){alert(e.message||"Data gagal dimuat.");return false}}

function loginShell(inner){document.getElementById("app").classList.add("hidden");const el=document.getElementById("loginScreen");el.classList.remove("hidden");el.innerHTML=`<div class="login-card">${inner}</div>`;return el}
function showLogin(message=""){const el=loginShell(`<div class="login-logo">W</div><h1>WaliNet</h1><p class="sub">Panel Admin & Manajemen WiFi</p>${message?`<div class="error">${esc(message)}</div>`:""}<form id="loginForm"><div class="field"><label>Username</label><input id="loginUser" autocomplete="username" required></div><div class="field"><label>Password</label><input id="loginPass" type="password" autocomplete="current-password" required></div><button class="btn full" type="submit">Masuk ke Panel</button></form><button id="billBtn" class="btn secondary full" style="margin-top:10px">Cek Tagihan Pelanggan</button><p class="muted" style="margin:14px 0 0;text-align:center">Gunakan akun aktif yang tersimpan pada sheet Pengguna.</p>`);document.getElementById("loginForm").onsubmit=async e=>{e.preventDefault();const btn=e.target.querySelector("button");btn.disabled=true;btn.textContent="Memeriksa...";try{const r=await api("login",{username:document.getElementById("loginUser").value.trim(),password:document.getElementById("loginPass").value});if(!r.success){showLogin(r.message||"Username atau password salah.");return}currentUser=r.user||{};sessionStorage.setItem("walinet_session",JSON.stringify(currentUser));el.classList.add("hidden");document.getElementById("app").classList.remove("hidden");await loadRemoteData();render()}catch(err){showLogin(err.message)}};document.getElementById("billBtn").onclick=showPublicBill}

function showPublicBill(){const el=loginShell(`<div class="login-logo">W</div><h1>Cek Tagihan</h1><p class="sub">Masukkan ID pelanggan atau nomor HP.</p><form id="billForm"><div class="field"><label>ID Pelanggan / No. HP</label><input id="billKey" placeholder="Contoh: PLG001 atau 08xxxxxxxxxx" required></div><button class="btn full" type="submit">Cek Tagihan</button></form><button id="backLogin" class="btn secondary full" style="margin-top:10px">Kembali ke Login Admin</button><div id="billResult"></div>`);document.getElementById("backLogin").onclick=()=>showLogin();document.getElementById("billForm").onsubmit=async e=>{e.preventDefault();const key=document.getElementById("billKey").value.trim(),box=document.getElementById("billResult");box.innerHTML=`<div class="card"><p class="muted">Memuat tagihan...</p></div>`;try{const r=await api("bill",{key});if(!r.success){box.innerHTML=`<div class="error">${esc(r.message||"Pelanggan tidak ditemukan.")}</div>`;return}const c=r.customer,p=r.payments||[],last=p.length?p[p.length-1]:null,paid=last&&String(last["Status"]||last.status).toLowerCase()==="lunas";box.innerHTML=`<div class="card"><h3>${esc(c["Nama"]||"")}</h3><div class="row"><span>ID Pelanggan</span><b>${esc(c["ID Pelanggan"]||c["ID"]||"-")}</b></div><div class="row"><span>No. HP</span><b>${esc(c["No HP"]||c["Nomor HP"]||"-")}</b></div><div class="row"><span>Paket</span><b>${esc(c["Nama Paket"]||c["Paket"]||c["ID Paket"]||"-")}</b></div><div class="row"><span>Tagihan</span><b>${money(c["Harga"])}</b></div><div class="row"><span>Jatuh Tempo</span><b>${esc(c["Jatuh Tempo"]||c["Tanggal Jatuh Tempo"]||"-")}</b></div><div class="row"><span>Status</span>${badge(paid?"Lunas":(c["Status"]||"Belum Bayar"))}</div>${last?`<div class="row"><span>Pembayaran terakhir</span><span>${esc(last["Periode"]||last["Keterangan"]||"-")}<br><b>${money(last["Nominal"]||last["Jumlah"])}</b></span></div>`:""}</div>`}catch(err){box.innerHTML=`<div class="error">${esc(err.message)}</div>`}}}

function nav(){document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.route===route))}
function dashboard(s){const t=data.customers.length,paidIds=new Set(data.payments.filter(x=>String(x.status).toLowerCase()==="lunas").map(x=>x.customerId)),paid=data.customers.filter(x=>paidIds.has(x.id)).length,arrears=Math.max(0,t-paid),income=data.payments.filter(x=>String(x.status).toLowerCase()==="lunas").reduce((v,x)=>v+x.amount,0),bill=data.customers.reduce((v,x)=>v+x.price,0),tunggakan=Math.max(0,bill-income);s.innerHTML=`<p class="hello">Selamat datang, ${esc(currentUser.name||"Admin")}</p><h1 class="title">Dashboard</h1><select class="period"><option>Data saat ini</option></select><div class="grid"><div class="stat"><span class="icon">P</span><strong>${t}</strong><small>Total Pelanggan</small></div><div class="stat"><span class="icon">✓</span><strong>${paid}</strong><small>Sudah Bayar</small></div><div class="stat"><span class="icon">!</span><strong>${arrears}</strong><small>Menunggak</small></div><div class="stat"><span class="icon">Rp</span><strong>${money(income)}</strong><small>Pemasukan</small></div></div><div class="card"><div class="section-head"><h3>Menu Cepat</h3></div><div class="action-grid"><button class="btn action-card" id="addCustomerBtn">+ Tambah Pelanggan</button><button class="btn secondary action-card" id="customerListBtn">Daftar Pelanggan</button></div></div><div class="card"><h3>Status Pembayaran</h3><div class="row"><span>Sudah bayar</span><b class="amount-success">${paid} pelanggan</b></div><div class="row"><span>Belum bayar</span><b class="amount-danger">${arrears} pelanggan</b></div></div><div class="card"><h3>Tagihan Bulan Ini</h3><div class="row"><span>Total tagihan</span><b>${money(bill)}</b></div><div class="row"><span>Sudah dibayar</span><b class="amount-success">${money(income)}</b></div><div class="row"><span>Tunggakan</span><b class="amount-danger">${money(tunggakan)}</b></div></div>`;document.getElementById("addCustomerBtn").onclick=()=>{route="addCustomer";render()};document.getElementById("customerListBtn").onclick=()=>{route="customers";render()}}

function customers(s){s.innerHTML=`<div class="section-head"><h1 class="title">Pelanggan</h1><button class="btn" id="addCustomerTop">+ Tambah</button></div><div class="search"><input id="q" placeholder="Cari nama / nomor HP / ID..."><button class="btn secondary" id="refreshBtn">↻</button></div><div id="list"></div>`;const draw=()=>{const q=(document.getElementById("q").value||"").toLowerCase(),list=data.customers.filter(x=>`${x.id} ${x.name} ${x.phone}`.toLowerCase().includes(q));document.getElementById("list").innerHTML=list.map(x=>`<div class="card"><div class="customer"><div class="avatar">${esc((x.name||"?")[0])}</div><div class="customer-main"><b>${esc(x.name)}</b><small>${esc(x.phone)} · ${esc(x.package)} · ${money(x.price)}</small></div>${badge(x.status)}</div><div class="row"><span class="muted">Jatuh tempo</span><span>${esc(x.due||"-")}</span></div></div>`).join("")||`<div class="empty">Pelanggan tidak ditemukan</div>`};document.getElementById("q").oninput=draw;document.getElementById("refreshBtn").onclick=async()=>{await loadRemoteData();draw()};document.getElementById("addCustomerTop").onclick=()=>{route="addCustomer";render()};draw()}

function addCustomerPage(s){const opts=data.packages.filter(p=>String(p["Status"]||"Aktif").toLowerCase()!=="nonaktif").map(p=>`<option value="${esc(p["ID Paket"]||p["Paket"]||"")}">${esc(p["Nama Paket"]||p["ID Paket"]||"Paket")} ${p["Harga"]?"· "+money(p["Harga"]):""}</option>`).join("");s.innerHTML=`<h1 class="title">Tambah Pelanggan</h1><div class="card"><form id="customerForm"><div class="field"><label>ID Pelanggan</label><input id="cId" placeholder="Kosongkan untuk otomatis"></div><div class="field"><label>Nama Pelanggan *</label><input id="cName" required></div><div class="field"><label>Nomor HP *</label><input id="cPhone" inputmode="tel" required></div><div class="field"><label>Alamat</label><textarea id="cAddress"></textarea></div><div class="field"><label>Paket WiFi *</label><select id="cPackage" required><option value="">Pilih paket</option>${opts}</select></div><div class="field"><label>Username MikroTik</label><input id="cMikrotik" placeholder="Opsional"></div><div class="field"><label>Tipe</label><select id="cType"><option value="PPPoE">PPPoE</option><option value="Hotspot">Hotspot</option><option value="Voucher">Voucher</option></select></div><div class="field"><label>Tanggal Jatuh Tempo</label><input id="cDue" type="date"></div><div class="field"><label>Status</label><select id="cStatus"><option>Aktif</option><option>Nonaktif</option></select></div><div id="formMessage"></div><div class="form-actions"><button type="button" class="btn secondary" id="cancelCustomer">Batal</button><button type="submit" class="btn">Simpan Pelanggan</button></div></form></div>`;document.getElementById("cancelCustomer").onclick=()=>{route="customers";render()};document.getElementById("customerForm").onsubmit=async e=>{e.preventDefault();const btn=e.target.querySelector("button[type=submit]"),box=document.getElementById("formMessage");if(!currentUser?.token){box.innerHTML=`<div class="error">Sesi admin belum memiliki token. Silakan logout lalu login kembali.</div>`;return}btn.disabled=true;btn.textContent="Menyimpan...";try{const r=await api("addcustomer",{token:currentUser.token,id:document.getElementById("cId").value.trim(),name:document.getElementById("cName").value.trim(),phone:document.getElementById("cPhone").value.trim(),address:document.getElementById("cAddress").value.trim(),packageId:document.getElementById("cPackage").value.trim(),mikrotik:document.getElementById("cMikrotik").value.trim(),type:document.getElementById("cType").value,status:document.getElementById("cStatus").value,due:document.getElementById("cDue").value});if(!r.success){box.innerHTML=`<div class="error">${esc(r.message||"Gagal menyimpan pelanggan.")}</div>`;btn.disabled=false;btn.textContent="Simpan Pelanggan";return}await loadRemoteData();route="customers";render()}catch(err){box.innerHTML=`<div class="error">${esc(err.message)}</div>`;btn.disabled=false;btn.textContent="Simpan Pelanggan"}}}

function payments(s){s.innerHTML=`<h1 class="title">Pembayaran</h1><div class="search"><input id="pq" placeholder="Cari pelanggan..."><button class="btn" id="pr">↻</button></div><div id="plist" class="card table-like"></div>`;const draw=()=>{const q=(document.getElementById("pq").value||"").toLowerCase(),list=data.payments.filter(x=>`${x.customer} ${x.customerId} ${x.period}`.toLowerCase().includes(q));document.getElementById("plist").innerHTML=list.map(x=>`<div class="row"><div><b>${esc(x.customer||x.customerId)}</b><div class="muted">${esc(x.period||"-")} · ${esc(x.date||"-")}</div></div><div style="text-align:right"><b>${money(x.amount)}</b><br>${badge(x.status)}</div></div>`).join("")||`<div class="empty">Belum ada pembayaran</div>`};document.getElementById("pq").oninput=draw;document.getElementById("pr").onclick=async()=>{await loadRemoteData();draw()};draw()}

function reports(s){const a=data.customers.filter(x=>!data.payments.some(p=>p.customerId===x.id&&String(p.status).toLowerCase()==="lunas"));s.innerHTML=`<h1 class="title">Laporan</h1><div class="switch"><button class="selected" id="m">Bulanan</button><button id="a">Tunggakan</button></div><div id="rb"></div>`;const b=document.getElementById("rb");function monthly(){b.innerHTML=`<div class="grid"><div class="stat"><strong>${data.customers.length}</strong><small>Pelanggan</small></div><div class="stat"><strong>${money(data.customers.reduce((v,x)=>v+x.price,0))}</strong><small>Total Tagihan</small></div><div class="stat"><strong>${money(data.payments.filter(x=>String(x.status).toLowerCase()==="lunas").reduce((v,x)=>v+x.amount,0))}</strong><small>Sudah Dibayar</small></div><div class="stat"><strong>${money(a.reduce((v,x)=>v+x.price,0))}</strong><small>Tunggakan</small></div></div><div class="card"><h3>Rekap Pelanggan</h3>${data.customers.map(x=>`<div class="row"><span>${esc(x.name)}<br><small class="muted">${esc(x.package)}</small></span>${badge(a.some(y=>y.id===x.id)?"Belum Bayar":"Lunas")}</div>`).join("")}</div>`}function arrears(){b.innerHTML=`<div class="card"><h3>${a.length} Pelanggan Menunggak</h3><h2 class="amount-danger">${money(a.reduce((v,x)=>v+x.price,0))}</h2></div>${a.map(x=>`<div class="card"><div class="customer"><div class="avatar">${esc((x.name||"?")[0])}</div><div class="customer-main"><b>${esc(x.name)}</b><small>${esc(x.package)} · Jatuh tempo ${esc(x.due||"-")}</small></div><b class="amount-danger">${money(x.price)}</b></div></div>`).join("")||`<div class="empty">Tidak ada tunggakan.</div>`}`}document.getElementById("m").onclick=()=>{monthly();m.classList.add("selected");a.classList.remove("selected")};document.getElementById("a").onclick=()=>{arrears();a.classList.add("selected");m.classList.remove("selected")};monthly()}

function more(s){s.innerHTML=`<h1 class="title">Lainnya</h1><div class="card"><button id="billMenu" class="row" style="width:100%;border:0;background:none;text-align:left"><b>Cek Tagihan Pelanggan</b><span>›</span></button><button id="addMenu" class="row" style="width:100%;border:0;background:none;text-align:left"><b>Tambah Pelanggan</b><span>›</span></button><div class="row"><b>Paket WiFi</b><span>›</span></div>${isAdmin()?`<button id="accountsBtn" class="row" style="width:100%;border:0;background:none;text-align:left"><b>Akun Pengguna</b><span>›</span></button>`:""}<div class="row"><b>Pengaturan</b><span>›</span></div></div><div class="card"><b>${esc(currentUser.name)}</b><div class="muted">${esc(currentUser.role)} · @${esc(currentUser.username)}</div><button id="logout" class="btn danger logout">Keluar</button></div>`;document.getElementById("billMenu").onclick=showPublicBill;document.getElementById("addMenu").onclick=()=>{route="addCustomer";render()};if(document.getElementById("accountsBtn"))document.getElementById("accountsBtn").onclick=()=>{route="accounts";render()};document.getElementById("logout").onclick=logout}

function accountsPage(s){if(!isAdmin()){s.innerHTML=`<h1 class="title">Akses Ditolak</h1><div class="card">Menu ini hanya dapat dibuka oleh Admin.</div>`;return}s.innerHTML=`<h1 class="title">Akun Pengguna</h1><div class="card"><p>Pengelolaan akun dilakukan melalui sheet <b>Pengguna</b>. Untuk keamanan, password tidak ditampilkan di aplikasi.</p></div>`}

function render(){if(!currentUser)return showLogin();nav();const s=document.getElementById("screen");if(route==="dashboard")dashboard(s);else if(route==="customers")customers(s);else if(route==="addCustomer")addCustomerPage(s);else if(route==="payments")payments(s);else if(route==="reports")reports(s);else if(route==="accounts")accountsPage(s);else more(s)}

document.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>{route=b.dataset.route;render()});document.getElementById("logoutTop").onclick=logout;document.getElementById("menuBtn").onclick=()=>{route="more";render()};if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});

(function start(){const saved=sessionStorage.getItem("walinet_session");if(saved){try{currentUser=JSON.parse(saved);document.getElementById("loginScreen").classList.add("hidden");document.getElementById("app").classList.remove("hidden");loadRemoteData().then(()=>render()).catch(()=>logout());return}catch(e){sessionStorage.removeItem("walinet_session")}}showLogin()})();
